export { Course, type ICourse } from './course'
export { Student, type IStudent } from './student'
export { Teacher, type ITeacher } from './teacher'
export { University, type IUniversity } from './university'
export { Enrollment, type IEnrollment } from './enrollment'
export { CourseCategory, type ICourseCategory } from './courseCategory'
export { CourseFormat, type ICourseFormat } from './courseFormat'
export { EnrollmentStatus, type IEnrollmentStatus } from './enrollmentStatus'
